-- data-3 / RideOn Club Supabase schema
-- Supabase SQL Editor에서 한 번 실행하세요.

create extension if not exists pgcrypto;

create table if not exists public.rbc_notices (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_name text not null,
  password_hash text not null,
  is_pinned boolean not null default false,
  views integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rbc_free_posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_name text not null,
  password_hash text not null,
  views integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rbc_gallery (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author_name text not null,
  password_hash text not null,
  image_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rbc_regular_meetings (
  id bigint generated by default as identity primary key,
  title text not null,
  region text not null,
  meeting_date date not null,
  location text,
  capacity integer not null check (capacity > 0),
  content text,
  author_name text not null default '운영진',
  host_name text,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rbc_small_gatherings (
  id bigint generated by default as identity primary key,
  title text not null,
  region text not null,
  gathering_date date not null,
  location text,
  capacity integer not null check (capacity > 0),
  content text,
  host_name text not null,
  password_hash text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.rbc_regular_meeting_registrations (
  id bigint generated by default as identity primary key,
  meeting_id bigint not null references public.rbc_regular_meetings(id) on delete cascade,
  name text not null,
  phone text not null,
  password_hash text not null,
  memo text,
  created_at timestamptz not null default now()
);

create table if not exists public.rbc_small_gathering_registrations (
  id bigint generated by default as identity primary key,
  gathering_id bigint not null references public.rbc_small_gatherings(id) on delete cascade,
  name text not null,
  phone text not null,
  password_hash text not null,
  memo text,
  created_at timestamptz not null default now()
);

-- 같은 연락처의 중복 신청 방지
create unique index if not exists uq_regular_phone on public.rbc_regular_meeting_registrations(meeting_id, phone);
create unique index if not exists uq_small_phone on public.rbc_small_gathering_registrations(gathering_id, phone);

-- GitHub Pages의 anon 클라이언트가 CRUD할 수 있도록 데모용 정책.
-- 실제 운영 전에는 관리자/회원 인증과 RPC/Edge Function으로 교체하는 것을 권장합니다.
alter table public.rbc_notices enable row level security;
alter table public.rbc_free_posts enable row level security;
alter table public.rbc_gallery enable row level security;
alter table public.rbc_regular_meetings enable row level security;
alter table public.rbc_small_gatherings enable row level security;
alter table public.rbc_regular_meeting_registrations enable row level security;
alter table public.rbc_small_gathering_registrations enable row level security;

drop policy if exists "public all notices" on public.rbc_notices;
create policy "public all notices" on public.rbc_notices for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all free" on public.rbc_free_posts;
create policy "public all free" on public.rbc_free_posts for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all gallery" on public.rbc_gallery;
create policy "public all gallery" on public.rbc_gallery for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all meetings" on public.rbc_regular_meetings;
create policy "public all meetings" on public.rbc_regular_meetings for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all gatherings" on public.rbc_small_gatherings;
create policy "public all gatherings" on public.rbc_small_gatherings for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all meeting regs" on public.rbc_regular_meeting_registrations;
create policy "public all meeting regs" on public.rbc_regular_meeting_registrations for all to anon, authenticated using (true) with check (true);

drop policy if exists "public all gathering regs" on public.rbc_small_gathering_registrations;
create policy "public all gathering regs" on public.rbc_small_gathering_registrations for all to anon, authenticated using (true) with check (true);

-- Realtime publication에 필요한 테이블 추가
do $$
begin
  begin alter publication supabase_realtime add table public.rbc_notices; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_free_posts; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_gallery; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_regular_meetings; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_small_gatherings; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_regular_meeting_registrations; exception when duplicate_object then null; end;
  begin alter publication supabase_realtime add table public.rbc_small_gathering_registrations; exception when duplicate_object then null; end;
end $$;
